@startuml

interface Iterable<Page>{
}

package Carnet{
package monde{
    class Monde extends SujetObservateur{
    + Page pageActuelle
    + void pageSuivante()
    + void pagePrecedente()
    + void versPage(int numeroPage)
    + Monde()
    + Page aCommePageAcceuil()
    + Page aCommePageFin()
    + void supprimerPage(int numeroPage)
    + void ajouterPageAccueil(Date dateDebut, Date dateFin, String Auteur, String Participant...)
    + void ajouterPageJourPhoto(Date date, String info, String lienPhoto)
    + void ajouterPageJourPhotoMap(Date date, String info, String lienPhoto, int coordonnee)
    }
    Monde --"1" GestionnairePage

    class SujetObservateur{
    + void ajouterObservateur(Observateur o)
    + void supprimerObservateur(Observateur o)
    + void notifierObservateur()
    }

    class GestionnairePage {
    + GestionnairePage()
    + Page getPageAccueil()
    + Page getDernierePage()
    + Page getPage(Date date)
    + void ajouterPage(Page page...)
    + void supprimerPage(Page page...)
    + int nbPage()
    }
    GestionnairePage ..|> Iterable
    GestionnairePage --"*" Page

    class Page{
    - int numeroPage
    + Page()
    + boolean estUnePageAccueil()
    + boolean estUnePageJour()
    + Vignette getVignette()
    }

    class PageAccueil extends Page{
    + PageAccueil(Date dateDebut, Date dateFin, String Auteur, String Participant ...)
    - ArrayList<String> Participant
    - String Auteur
    - Date dateDebut
    - Date dateFin
    }

    abstract class PageJour extends Page{
    - Date date
    - String info
    }

    class PageJourPhoto extends PageJour{
    - String lienPhoto
    }


    class PageJourPhotoMap extends PageJourPhoto{
    - int coordonnee
    }

'    class Vignette{
'    + Vignette()
'    }
'
'    class VignettePageAccueil extends Vignette{
'    + String titre
'    + VignettePageAccueil()
'    }
'
'    abstract class VignettePageJour extends Vignette{
'    + String info
'    + VignettePageJour()
'    }
'
'    class VignettePageJourPhoto extends VignettePageJour{
'    + String lienPhoto
'    + VignettePageJourPhoto()
'    }
'
'    class VignettePageJourPhotoMap extends VignettePageJourPhoto{
'    + int coordonnee
'    + VignettePageJourPhotoMap()
'    }



}

package outils{
    class FabriqueNumero{
    - int numeroJour
    + FabriqueNumero getinstance()
    + int getNumeroJour()
    }
    FabriqueNumero --"1" FabriqueNumero
    }

package view{
    interface Observateur{
    + void reagir()
    }
    Observateur --"1" Monde

    class VueMonde implements Observateur{
    + void reagir()
    }
    VueMonde --"*" VuePage

    abstract class  VuePage implements Observateur{
    + void reagir()
    }


    class VuePageAcceuil extends VuePage{
    + void sauvegarder()
    + void reagir()
    + void changerPage()
    }
'    VuePageAcceuil --"4" Label


    abstract class VuePageJour extends VuePage{
    + void sauvegarder()
    + void reagir()
    + void pageSuivante()
    + void pagePrecedente()
    }
'    VuePageJour --"2" Label


    class VuePageTextPhoto extends VuePageJour{
    + void reagir()
    }
'    VuePageTextPhoto --"1" Photo
'    VuePageTextPhoto --"1" Label

    class VuePageTextPhotoMap extends VuePageTextPhoto{
    + void reagir()
    }
'    VuePageTextPhotoMap -- "1" MapView

    class VueMondeVignette extends VuePage{
    + void reagir()
    }
    VueMondeVignette --"*" VueVignette

    abstract class VueVignette {
    + VueVignette()
    + void supprimerPage()
    + void reagir()
    }

    class VueVignetteAjouterPage extends VueVignette{
    + void ajouterPage()
    + void reagir()
    }

    class VueVignettePageAcceuil extends VueVignette{
    + void supprimerPage()
    + void reagir()
    }
'    VueVignettePageAcceuil --"1" Label

    class VueVignettePageTextPhoto extends VueVignette{
    + void supprimerPage()
    + void reagir()
    }
'    VueVignettePageTextPhoto --"1" Photo
'    VueVignettePageTextPhoto --"1" Label

    class VueVignettePageTextPhotoMap extends VueVignettePageTextPhoto{
    + void supprimerPage()
    + void reagir()
    }
'    VueVignettePageTextPhotoMap --"1" MapView

    class VueAjouterPage extends VuePage{
    + void ajouterPage()
    + void reagir()
    }


    }
}
SujetObservateur -"*" Observateur
'VuePage --"1" Monde


@enduml